### ISSUE TITLE
spec. kubernetes.kubeControllerManager.nodeCIDRMaskSize is unable to set values

### ISSUE THREAD

**Issue by neo-liang-sap** [kyma-incubator/terraform-provider-gardener#69] opened 2020-02-25 04:12 UTC
Hi,
In my test using latest terraform-provider-gardener against Canary landscape using AWS provider, i found that spec. kubernetes.kubeControllerManager.nodeCIDRMaskSize is unable to set values, whatever i set to it, the final shoot cluster set 24 (which is default) for this value.

In my main.tf file i set this value like this

```
spec {
  kubernetes {
    kube_controller_manager {
        node_cidr_mask_size = 16
      }
  }
}
```
and i found in the final shoot, the value of `node_cidr_mask_size` is 24

I and @dansible looked into the code, we noticed that this value is injected at https://github.com/kyma-incubator/terraform-provider-gardener/blob/bd0f219e440406ade6be6120e3f665838100ac70/flatten/flatten_spec.go#L269

i tried to debug this line but i didn't find any error which might causing this issue.

I also tried to hard code inject value in `terraform-provider-gardener` for this line for didn't help

i tried this
```
	if in.KubeControllerManager != nil {
		manager := make(map[string]interface{})
		if in.KubeControllerManager.FeatureGates != nil {
			// manager["node_cidr_mask_size"] = in.KubeControllerManager.NodeCIDRMaskSize
			f := 16
			manager["node_cidr_mask_size"] = &f
                         # i also tried this but still failed to set value
                         # manager["node_cidr_mask_size"] = f
		}
		att["kube_controller_manager"] = []interface{}{manager}
```

whatever i tried , the CIDR is 24 (default value)

Is this value an bug from `terraform-provider-gardener` e.g. error format while sending API to gardener server?

Thanks!

-Neo

**Comment by rakesh-garimella** [comment] 2020-03-03 09:04
Hi @neo-liang-sap  can you please provide the complete terraform manifest file so that I can try to reproduce the issue.

**Comment by neo-liang-sap** [comment] 2020-03-03 09:15
Hi @rakesh-garimella ,

update:
i removed internal github url per @dansible suggestion - feel free ping me if you still needs that url
thanks

Thanks for taking caring of this issue.

We have an wrapper to call `terraform-provider-gardener` but you can see the complete tf file at 

I've grant you access to this repo.

For specified `node_cidr_mask_size` you can refer to this line in file above

We pass an value like `10.20.20.0/16` to `var.gardener_shoot_vpc_cidr` and `node_cidr_mask_size` gets the value of `16`, but in the file shoot this value is changed to `24`

/cc @dansible @tedteng

Thanks

**Comment by dansible** [comment] 2020-03-06 14:51
We're using this regex which just takes the `/*` subnet from the `gardener_shoot_vpc_cidr` var:

```
     kube_controller_manager {
        node_cidr_mask_size = regex("[0-9]{2}$", var.gardener_shoot_vpc_cidr)
      }
```

So when providing a value like `gardener_shoot_vpc_cidr = 10.0.0.0/16`, the `terraform plan/apply` diff correctly shows `node_cidr_mask_size = 16` but when applying, we get this error 

```
Error: Shoot.core.gardener.cloud "idefix-su1" is invalid: spec.kubernetes.kubeControllerManager.nodeCIDRMaskSize: Invalid value: 24: field is immutable
```

I'm wondering where that `24` value is being injected? If I inspect the shoot spec live in Gardener, it also shows that the value is `nodeCIDRMaskSize: 16`

**Comment by rakesh-garimella** [comment] 2020-03-06 18:27
Thanks @dansible and @neo-liang-sap  for the inputs the problem is we are not passing the `nodeCIDRMaskSize` value from the `.tf` file to the `gardener` so it assumes a default of `24`. We need to add the logic in the function here: https://github.com/kyma-incubator/terraform-provider-gardener/blob/master/expand/expand_spec.go#L273

So eventhough you pass `/16` as the CIDR Mask, the default `/24` is assumed. The second issue I think it cannot be changed once you have set the value for the CIDR mask.

**Comment by neo-liang-sap** [comment] 2020-03-07 06:33
Hi @rakesh-garimella ,
I tried to implement the logic as you mentioned in `expand_spec.go` but no luck, still i got `24` in final shoot building
```
	if v, ok := in["node_cidr_mask_size"].(*int32); ok {
		obj.NodeCIDRMaskSize = v
	}
```
meanwhile i tried force value injection in `flatten_spec.go` but also didn't help
you can see my PR for demo in https://github.com/kyma-incubator/terraform-provider-gardener/pull/70
i tried different value setting in `expand_spec.go` like this but neither work
```
	if v, ok := in["node_cidr_mask_size"].(int32); ok {
		obj.NodeCIDRMaskSize = &v
	}
```
Thanks!

/cc @dansible

**Comment by rakesh-garimella** [comment] 2020-03-07 10:29
hmm looking [here](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L130) it does not give example for  nodeCIDRMaskSize.

**Comment by neo-liang-sap** [comment] 2020-03-09 11:10
Hi @danielfoehrKn :

Thanks for your comments in https://github.com/gardener/gardener/issues/2017#issuecomment-596462156 - actually i'm opening this issue before reaching at https://github.com/gardener/gardener/issues/2017

Hi @rakesh-garimella ,

I raised this issue to gardener per our slack conversation today and they confirmed everything is ok from gardener api side... anything we could get more information regarding this `nodeCIDRMaskSIze`issue?

Thanks both!

/cc @dansible

**Comment by timuthy** [comment] 2020-03-23 07:02
> hmm looking here it does not give example for nodeCIDRMaskSize.

https://github.com/gardener/gardener/blob/e4db94cc68d8472cf50e261928aa5a030d54b0e9/example/90-shoot.yaml#L131

**Comment by rakesh-garimella** [comment] 2020-07-20 06:57
The fix
```
-               obj.NodeCIDRMaskSize = v
+       if v, ok := in["node_cidr_mask_size"].(int); ok {
+               s := int32(v)
+.              obj.NodeCIDRMaskSize = &s
+       }
```

does not seem to reflect the node cidr size. Need to understand whats going wrong.

**Comment by rakesh-garimella** [comment] 2020-09-30 11:38
Closing this bug as its not maintained actively.

**Closed as completed by rakesh-garimella** 2020-09-30 11:38 UTC
Labels: kind/bug, area/cli
